[project]
name = "estoque-casd"
version = "0.1.0"
description = "Sistema para controle de estoque do Centro Acadêmico Santos Dumont (CASD)"
readme = "README.md"
authors = [
    { name = "Arthur Vianna", email = "viannarth@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "python-dotenv>=1.2.3",
]
