# Generated by Django 6.1.1 on 2026-10-10 01:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo_estoque', models.CharField(choices=[('CASD', 'Casd'), ('ZELADORIA', 'Zela')], max_length=20)),
                ('quant_total', models.PositiveBigIntegerField()),
                ('quant_uso', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ap', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nome', models.CharField(max_length=255)),
                ('nome_user', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('limit_data', models.DateTimeField()),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.item')),
                ('id_morador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.morador')),
            ],
        ),
        migrations.CreateModel(
            name='Log_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_aparelho', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)])),
                ('event_data', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=20)),
                ('id_admin', models.ForeignKey(db_column='ID_ADMIN', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log_Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_aparelho', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)])),
                ('event_data', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=20)),
                ('id_empresitmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.emprestimo')),
            ],
        ),
        migrations.CreateModel(
            name='Uso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('limit_data', models.DateTimeField()),
                ('id_admin', models.ForeignKey(db_column='ID_ADMIN', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.item')),
            ],
        ),
        migrations.CreateModel(
            name='Log_uso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_aparelho', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(15)])),
                ('event_data', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=20)),
                ('id_uso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.uso')),
            ],
        ),
    ]
