# Generated by Django 6.1.1 on 2026-10-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quant_uso',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
